version: 2
updates:
- package-ecosystem: npm
  directory: "/desktop"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.8
  - dependency-name: eslint-plugin-react
    versions:
    - 7.21.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prettier
    versions:
    - 2.0.5
- package-ecosystem: cargo
  directory: "/packer"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: anyhow
    versions:
    - 1.0.38
    - 1.0.39
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
  - dependency-name: serde_yaml
    versions:
    - 0.8.15
    - 0.8.16
  - dependency-name: tar
    versions:
    - 0.4.32
  - dependency-name: sha2
    versions:
    - 0.9.2
  - dependency-name: data-encoding
    versions:
    - 2.3.1
